// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class IAMCredentialsRetry: IAMCredentialsStub {
    let inner: any IAMCredentialsStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any IAMCredentialsStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamCredentialsV1.GenerateAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateAccessTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIamCredentialsV1.GenerateAccessTokenResponse
          in
          return try await self.inner.generateAccessToken(request: r, options: o)
        })
    }

    public func generateIdToken(
      request: GenerateIdTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamCredentialsV1.GenerateIdTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateIdTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIamCredentialsV1.GenerateIdTokenResponse
          in
          return try await self.inner.generateIdToken(request: r, options: o)
        })
    }

    public func signBlob(
      request: SignBlobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamCredentialsV1.SignBlobResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SignBlobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIamCredentialsV1.SignBlobResponse
          in
          return try await self.inner.signBlob(request: r, options: o)
        })
    }

    public func signJwt(
      request: SignJwtRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamCredentialsV1.SignJwtResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SignJwtRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIamCredentialsV1.SignJwtResponse
          in
          return try await self.inner.signJwt(request: r, options: o)
        })
    }
  }
}
