// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class IAMCredentialsLogging: IAMCredentialsStub {
    let inner: any IAMCredentialsStub
    let logger: Logger

    public init(_ inner: any IAMCredentialsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-iam-credentials-v1"
      logger[metadataKey: "gcp.client.service"] = "iamcredentials"
      logger[metadataKey: "gcp.experimental.swift.client"] = "IAMCredentials"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMCredentialsV1.GenerateAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAccessToken",
        action: {
          (r: GenerateAccessTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMCredentialsV1.GenerateAccessTokenResponse
          in
          return try await self.inner.generateAccessToken(request: r, options: o)
        })
    }

    public func generateIdToken(
      request: GenerateIdTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMCredentialsV1.GenerateIdTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateIdToken",
        action: {
          (r: GenerateIdTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMCredentialsV1.GenerateIdTokenResponse
          in
          return try await self.inner.generateIdToken(request: r, options: o)
        })
    }

    public func signBlob(
      request: SignBlobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMCredentialsV1.SignBlobResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "signBlob",
        action: {
          (r: SignBlobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMCredentialsV1.SignBlobResponse
          in
          return try await self.inner.signBlob(request: r, options: o)
        })
    }

    public func signJwt(
      request: SignJwtRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMCredentialsV1.SignJwtResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "signJwt",
        action: {
          (r: SignJwtRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMCredentialsV1.SignJwtResponse
          in
          return try await self.inner.signJwt(request: r, options: o)
        })
    }
  }
}
